### PR TITLE
[WIP] Refactor Repository

### LINKED ISSUE #237: Leave only desktop-related code in repository
The current repository has all files from facebook's react-native, plus files related to desktop implementation. On every merge with a new react-native update, we have a lot of conflicts to resolve due to this.
Microsoft's react-native has a cleaner repository that contains only their code - https://github.com/Microsoft/react-native-windows

We should clean up our repository to achieve the same result.

### PR DESCRIPTION
**Pull request by madhavarshney**
This PR refactors `react-native-desktop` to be an extension of `react-native` and removes code unrelated to desktop support, as discussed in #237.  This PR changes the existing functionality of `react-ntaive-desktop` in the following ways:

- Resolves #237
- Makes `react-native desktop` generate both `.bat` and `.sh` files
- Changes the build folder from `RNDesktopTest/desktop/` to `RNDesktopTest/desktop/build/`
- Moves all scripts (`build.sh`, `build.bat`, `run-desktop.bat.in`, and `run-desktop.sh.in`) to `RNDesktopTest/desktop/bin`

ToDo:

- [x] Clean up overall repository
- [x] Remove unmodified/unneeded files from `Libraries/`
- [ ] Remove code unrelated to the desktop implementation from `Libraries/**/*.desktop.js` 
  - _This **may make merging harder** - So should this be done?_ @MaxRis @vjkr
- [x] Create rnpm-plugin-desktop
- [ ] [WIP] Clean up and convert `local-cli` to add another platform to `react-native-cli`, supporting commands like `bundle --platform desktop`, `run-desktop`, etc.
- [ ] Update Jest tests with new structure of repository
- [x] Update documentation

Notes:

- `rnpm-plugin-desktop` currently contains commented code to install the correct version of `react-native-desktop` based on the version of `react-native` used in the target project.  This code should be enabled once releases of `react-native-desktop` corresponding to releases of `react-native` are published to npm.
- To test this PR, follow the [updated documentation](https://github.com/madhavarshney/react-native-desktop/blob/RefactorRepo/docs/CreateNewApp.md).  Just make sure to have this PR applied to your local `react-native-desktop` and install `react-native-desktop` in the target project through this command: `npm install status-im/react-native-desktop#pulls/259/head`.

### CODE REVIEW

**Comment by MaxRis** [comment]
Hey @madhavarshney , thank you for your PR! We have decided, finally, to merge react native v.0.55.4 first. I'm supposing to back to your PR just after the merge. Thanks

**Comment by vkjr** [comment]
@madhavarshney, is this PR ready for review? Can we remove "WIP" from header?

**Comment by madhavarshney** [comment]
@MaxRis - Should I base my PR on #263?  I might manually redo the changes on top of #263 instead of merging or rebasing my PR.

> is this PR ready for review?

@vkjr - Almost.  I just have to finish some things up and update the Jest tests.

**Comment by vkjr** [comment]
@madhavarshney, yes, that would be really good if you can base this PR on #263.

**Comment by MaxRis** [comment]
@madhavarshney as @vkjr mentioned, could you please do separate PRs to address each of described done things (or couple of related things) in the list above for this PR? This will be much more "readable"

**Comment by MaxRis** [comment]
Also please let me merge into master first. My PR requires rebase against master as well, that's not done yet. Thanks

**Comment by madhavarshney** [comment]
@MaxRis @vkjr - Sorry for the delay, it's going to take some time redoing the changes and opening separate PRs.

**Pull request closed without merging**
