### PR TITLE
Script to filter out not altered by Desktop files from original react…

### PR DESCRIPTION
**Pull request by MaxRis**
Script to filter out not altered by Desktop files from original react-native and auto-apply merge conflict resolution as theirs.

If some file not from the list in scripts/desktop-modified-files.txt and from original react-native will be altered, scripts/desktop-modified-files.txt should be extended to contain that source file.

### CODE REVIEW

**Comment by vkjr** [comment]
@MaxRis, great idea, should help a lot in merge!
Do I understand correctly that `desktop-modified-files.txt` isn't final yet and will be filled with more files that altered by desktop? (Like `Libraries/Components/ScrollView.js`)

**Comment by MaxRis** [comment]
@vkjr `desktop-modified-files.txt` should be final for this PR. It already contains `ScrollView.js`

**Comment by vkjr** [comment]
Sorry, missed it :)

**Comment by MaxRis** [comment]
@vkjr going to remove all ReactCommon/yoga/yoga/* files from the list, because we haven't made any changes to them.

**Comment by vkjr** [comment]
@MaxRis, good point! :)

**Pull request merged**
