### PR TITLE
Optional JavaScriptCore JS engine support #215

### PR DESCRIPTION
**Pull request by MaxRis**
Optional JavaScriptCore engine support on Linux:

- CMAKE option -DJAVASCRIPTCORE_ENABLED should be specified to enable build of JavaScriptCore and Facebook folly libs + react-native-desktop sources related to JavaScriptCore. (**ATTENTION**: Building of JavaScriptCore requires at least 8GB RAM, took 10+ GB of disk space and downloads 8GB of data from WebKit GitHub repository, lasts 15+ minutes)
- JavaScriptCoreExecutor class introduced to encapsulate all internal work related to JavaScriptCore

### CODE REVIEW

**Comment by vkjr** [comment]
@MaxRis, did I understand correctly that -DJAVASCRIPTCORE_ENABLED should be added in desktop/build.sh cmake invokation line?

**Comment by vkjr** [comment]
@MaxRis, Does react-native use JavaScriptCore as a default engine for ios and android apps?

**Comment by MaxRis** [comment]
@vkjr it should work, but at this time, it should be better just to modify corresponding option from OFF to ON, if you would like to try it https://github.com/status-im/react-native-desktop/pull/216/files#diff-af3b638bc2a3e6c650974192a53c7291R18
P.S. Next time you decide to change the option value back, you will need manually to remove CMake build cache.

**Comment by MaxRis** [comment]
@vkjr yes, on Mac OS and iOS there is available JavaScriptCore framework. On Android, not sure, but, probably, it's part of Android SDK.

**Pull request merged**
