### PR TITLE
Merging with react-native 0.56

### PR DESCRIPTION
**Pull request by MaxRis**
Desktop platform support was added to few more files according to https://github.com/facebook/react-native/pull/20825

### CODE REVIEW

**Comment by siphiuel** [comment]
@MaxRis thanks, this is massive!

I tried building status-react against this branch, but after running `npm start` I get this:
```
Loading dependency graph...(node:6017) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: PlatformViewPropTypes
  Paths: /Users/vvlasov/c/status-react/node_modules/react-native/Libraries/Components/View/PlatformViewPropTypes.desktop.js collides with /Users/vvlasov/c/status-react/node_modules/react-native/Libraries/Components/View/PlatformViewPropTypes.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (/Users/vvlasov/c/status-react/node_modules/react-native/node_modules/jest-haste-map/build/index.js:446:17)
    at workerReply (/Users/vvlasov/c/status-react/node_modules/react-native/node_modules/jest-haste-map/build/index.js:496:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6017) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6017) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Not sure what this means.

**Comment by MaxRis** [comment]
@siphiuel , sorry, I haven't mentioned anywhere, but already have PR for status-react https://github.com/status-im/status-react/pull/5932
Above error happens, because patch-package tool can't apply metro package patch and `desktop` platform is not get recognized by packager.
It looks like that one last known-standing issue is that `jest` unit tests are hanging for this PR in react-native-desktop. But status-react build, seems, works pretty well so far.

**Comment by siphiuel** [comment]
@MaxRis got it, thanks for explaining. Was also able to build and run that branch without any issues :)

**Comment by MaxRis** [comment]
@vkjr have found that failing unit test is using Button component.
For some earlier reasons we have reimplemented original Button in Button.desktop.js which is get drawn by ReactButton.qml Button QML item.
WIth following commit https://github.com/status-im/react-native-desktop/pull/340/commits/af37def8968ed06a55ed0f20db38f0660f60a8fc I've renamed our Button implementation to `NativeButton` and just `Button` will now use origin implementation of it from Button.js.
Please let me know if any objections or thoughts about that. Thanks!

**Comment by vkjr** [comment]
@MaxRis not at all :)

**Pull request merged**
