### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by madhavarshney**
### Motivation

A few updates and changes:

- Updated the base docker image from Ubuntu Trusty 14.04 to Ubuntu Xenial 16.04.
- Added a step to update NPM to v6.
- Updated package-lock.json.
- Removed CircleCI caching of `node_modules` in favor of [`npm ci`](https://docs.npmjs.com/cli/ci) + CircleCI caching of NPM cache.
- Removed the [cmake PPA](https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x) in favor of the official [cmake package](https://packages.ubuntu.com/xenial/cmake).

_Note: This PR does not upgrade Ubuntu to Bionic (18.04) because a [Qt 5.9 LTS PPA](https://launchpad.net/~beineri) is not available for that version.  If using Qt 5.11 is fine, then that can be done as well._

### Test Plan

N/A.

### Related PRs

N/A.

### Release Notes

This PR upgrades the npm lockfile version to npm@6.

### CODE REVIEW

**Comment by madhavarshney** [comment]
Don't know why jest isn't finishing... will debug.

**Comment by MaxRis** [comment]
@madhavarshney I've restarted ci build job.
Building against Qt 5.11 might be not really desired at the moment or we can discuss @vkjr @siphiuel @rcullito if we can upgrade to Qt 5.11 (it seems for upgrade no known issues exist at the moment)

**Comment by madhavarshney** [comment]
@MaxRis - Since CI build works, this PR is ready for review.

**Comment by madhavarshney** [comment]
Pushing another commit caused the same thing with the CI build, jest never finishes.  @MaxRis - Do you know why this is happening?

**Comment by MaxRis** [comment]
@madhavarshney I have never seen such issues before. From some time we started receiving allowed timeout overdue for jest tests and that was the reason of their random failures. But this might be not related.

**Comment by vkjr** [comment]
@maxris, @madhavarshney  I think moving to Qt 5.11 isn't a priority for now since it can break some components functionality. As far as I remember, @siphiuel had an issue at least with `Button` component when used Qt 5.10 instead of Qt 5.9.

**Comment by vkjr** [comment]
@madhavarshney, if circle ci build still hangs with the latest changes, that probably should be fixed.

**Comment by MaxRis** [comment]
@vkjr I've just discovered that ci build doesn't do cmake build at all and unit tests running as well
I'm going to resolve this in separate PR with `manageChildren` related changes, but the whole build is not stable and fails more often than passes.
I hope that I will able to merge my changes first and then will work to rebase changes from this PR (with fixes of not running cmake and unit tests) + will try to increase stability of build as well.

**Comment by vkjr** [comment]
@MaxRis, thanks for the explanation. Probably this PR should be closed and your PR mentioned as the one that will solve issues.

**Comment by madhavarshney** [comment]
> I've just discovered that ci build doesn't do cmake build at all and unit tests running as well

Oh, I actually did notice this.  I thought there aren't any unit tests currently and this was intentional.

> I hope that I will able to merge my changes first and then will work to rebase changes from this PR (with fixes of not running cmake and unit tests) + will try to increase stability of build as well.

Sure that's fine as well.

> if circle ci build still hangs with the latest changes, that probably should be fixed.

Yes, I'll see.  This bug seems to have been introduced with https://github.com/status-im/react-native-desktop/pull/279/commits/4b673ff76b847a34dcb8e4af63c5a2ba5debef96, although I don't know how that would affect anything.

> Probably this PR should be closed and your PR mentioned as the one that will solve issues.

This PR does a bunch of other things as well (if you read the description).  However it's up to you to decide if you'd like to close this PR and @MaxRis's PR can incorporate or discard these changes.

**Comment by MaxRis** [comment]
Current state of ci runs with PR https://github.com/status-im/react-native-desktop/pull/280 is following:
- At least 2 of 10 runs fails with jest test hanging forever ( so the issue is not introduced with current PR )
- At least 2 of 10 runs fails with jest tests errors
- At least 1 of 10 fails with unit tests errors ( it seems that integration test fails, but also seems that the timeout for second unit test there should be just increased to allow ubuntu_server to purge its sockets connections before new connection for new unit tests happened )

@madhavarshney @vkjr I will try to collect statistics for changes in this PR, if the percentage of failures is not increased we should be able to go with these changes, thank you!

**Comment by vkjr** [comment]
@maxris, @madhavarshney, probably I got it wrong. I thought that @maxris is going to incorporate all the changes from this PR into own. If this is not the case and changes will go on top of these ones, this one shouldn't be closed, sorry for the misunderstanding.

**Comment by madhavarshney** [comment]
@MaxRis - I figured out why CircleCI wasn't failing the build when CMake failed although I don't know why this happens.  Basically, having `cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j4` in one line causes the exit code to somehow be 0 instead of 1.  Changing that to the following fixed the issue.  Check the difference between https://circleci.com/gh/status-im/react-native-desktop/576 and https://circleci.com/gh/status-im/react-native-desktop/577.

```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j4
```

**Comment by MaxRis** [comment]
@madhavarshney great finding, thanks!

Regarding having of Docker image, I've created https://github.com/status-im/react-native-desktop/issues/284

**Comment by madhavarshney** [comment]
> I just rebased and jest still hangs.

@MaxRis - Hit this again.  It has to do something with timing.  I'm guessing it may also have to do something with `ubuntu-server.js` and the packager not starting fully before `jest` starts, although this is more of a wild guess.

**Comment by madhavarshney** [comment]
@MaxRis @vkjr - This PR is ready for review.

> - At least 2 of 10 runs fails with jest test hanging forever ( so the issue is not introduced with current PR )
> - At least 2 of 10 runs fails with jest tests errors
> - At least 1 of 10 fails with unit tests errors ( it seems that integration test fails, but also seems that the timeout for second unit test there should be just increased to allow ubuntu_server to purge its sockets connections before new connection for new unit tests happened )

I've noticed similar symptoms.

**Comment by madhavarshney** [comment]
ping @MaxRis @vkjr

**Comment by MaxRis** [comment]
@madhavarshney I will try to merge pending PRs during weekend, thanks

**Comment by madhavarshney** [comment]
No worries, take your time.

**Comment by MaxRis** [comment]
Hey @madhavarshney , could you please shape all available commits from this PR into single commit?
Also I'm wondering regarding changes in `package-lock.json`, I think that adding of this file into git was done by mistake and we should remove it + ignore in .gitignore

**Comment by madhavarshney** [comment]
@MaxRis - I squashed the CI commits into one commit, so now there two commits: `Update package-lock.json` and `CI Improvements`.  Regarding `package-lock.json`, it's a good idea to check it into Git to make sure `npm install` is reproducible on every machine and package versions are "locked".  The changes I have made are just checking in the automatically updated `package-lock.json` after updating NPM.  (Note: After this PR is merged you should be on NPM v5.10.0 or higher.)

**Comment by MaxRis** [comment]
@madhavarshney makes sense, thanks!

**Pull request merged**
